# Generated by Django 3.2.8 on 2021-12-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255, verbose_name='クラブ')),
            ],
            options={
                'verbose_name': 'クラブ名',
                'verbose_name_plural': 'クラブ名',
            },
        ),
        migrations.CreateModel(
            name='Player_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='選手名')),
            ],
            options={
                'verbose_name': 'プレイヤー名',
                'verbose_name_plural': 'プレイヤー名',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_day', models.DateField(verbose_name='試合日')),
                ('play_time', models.IntegerField(default=0, verbose_name='プレイタイム')),
                ('score', models.IntegerField(default=0, verbose_name='得点')),
                ('assist', models.IntegerField(default=0, verbose_name='アシスト数')),
                ('rebound', models.IntegerField(default=0, verbose_name='リバウンド数')),
                ('d_rebound', models.IntegerField(default=0, verbose_name='ディフェンスリバウンド数')),
                ('o_rebound', models.IntegerField(default=0, verbose_name='オフェンスリバウンド数')),
                ('steel', models.IntegerField(default=0, verbose_name='スティール数')),
                ('block', models.IntegerField(default=0, verbose_name='ブロック数')),
                ('playername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velca.player_name', verbose_name='プレイヤー名')),
            ],
            options={
                'verbose_name': 'スタッツ',
                'verbose_name_plural': 'スタッツ',
            },
        ),
        migrations.CreateModel(
            name='Player_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField(default=0, verbose_name='背番号')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_name', to='velca.player_name')),
                ('players_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velca.club')),
            ],
            options={
                'verbose_name': 'プレイヤー情報',
                'verbose_name_plural': 'プレイヤー情報',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_club', to='velca.club')),
                ('away_roster', models.ManyToManyField(related_name='away_roster', to='velca.Player_personal')),
                ('game_stats', models.ManyToManyField(to='velca.Stats')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_club', to='velca.club')),
                ('home_roster', models.ManyToManyField(related_name='home_roster', to='velca.Player_personal')),
            ],
            options={
                'verbose_name': '試合情報',
                'verbose_name_plural': '試合情報',
            },
        ),
    ]
