# Generated by Django 3.2.8 on 2021-10-20 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('velca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='assist',
            field=models.IntegerField(default=0, verbose_name='アシスト数'),
        ),
        migrations.AddField(
            model_name='player',
            name='block',
            field=models.IntegerField(default=0, verbose_name='ブロック数'),
        ),
        migrations.AddField(
            model_name='player',
            name='d_rebound',
            field=models.IntegerField(default=0, verbose_name='ディフェンスリバウンド数'),
        ),
        migrations.AddField(
            model_name='player',
            name='o_rebound',
            field=models.IntegerField(default=0, verbose_name='オフェンスリバウンド数'),
        ),
        migrations.AddField(
            model_name='player',
            name='play_time',
            field=models.IntegerField(default=0, verbose_name='プレイタイム'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='選手名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='rebound',
            field=models.IntegerField(default=0, verbose_name='リバウンド数'),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0, verbose_name='得点'),
        ),
        migrations.AddField(
            model_name='player',
            name='steel',
            field=models.IntegerField(default=0, verbose_name='スティール数'),
        ),
    ]
