# Generated by Django 3.2.8 on 2021-12-09 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_club', to='velca.club'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_club', to='velca.club'),
        ),
    ]
