# Generated by Django 3.2.8 on 2021-12-17 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('velca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='matchday',
            field=models.DateField(default=datetime.datetime(2021, 12, 17, 8, 24, 15, 826150, tzinfo=utc), verbose_name='試合日'),
            preserve_default=False,
        ),
    ]
