# Generated by Django 3.2.8 on 2022-02-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velca', '0003_alter_player_personal_player_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_personal',
            name='player_birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
